---
- name: Populate service facts
  service_facts:

- name: Cloudflared install tasks
  block:
    - name: Download cloudflared linux package
      shell: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    - name: Depackage cloudflared
      shell: sudo dpkg -i cloudflared-linux-amd64.deb
    - name: Install the tunnel as a systemd service
      shell: cloudflared service install {{ cloudflare_tunnel_token }}
  when:
    - ansible_facts.services['cloudflared.service'].state != 'running'
